YARDS_PITCH_WIDTH= 40
YARDS_PITCH_HEIGHT = 120
YARDS_ENDZONE_DEPTH = 25
YARDS_BRICK_MARK = 45

FRISBEE_DEFAULT_SCALE = 14

PITCH_WIDTH_RATIO = YARDS_PITCH_WIDTH/YARDS_PITCH_HEIGHT
PITCH_HEIGHT_RATIO = YARDS_PITCH_HEIGHT/YARDS_PITCH_HEIGHT
ENDZONE_DEPTH_RATIO = YARDS_ENDZONE_DEPTH/YARDS_PITCH_HEIGHT
BRICK_MARK_RATIO = YARDS_BRICK_MARK/YARDS_PITCH_HEIGHT


BRICK_MARK_POSITION = (PITCH_HEIGHT_RATIO/2-BRICK_MARK_RATIO)
ENDZONE_BACK = PITCH_HEIGHT_RATIO/2
ENDZONE_FRONT = PITCH_HEIGHT_RATIO/2 - ENDZONE_DEPTH_RATIO
ENDZONE_MID = PITCH_HEIGHT_RATIO/2 - ENDZONE_DEPTH_RATIO/2
SIDE_LINE_POSITION = PITCH_WIDTH_RATIO/2